### ISSUE TITLE
Missing query.06 from JOIN exercises

### ISSUE THREAD

**Issue by alessandro-maccario** [harsha547/ClassicModels-Database-Queries#1]
First of all: great repository!

I am missing the solution about the query n. 06 in the JOIN section, namely;

-- 6.How many orders have been placed by Herkku Gifts?

I think that the solution could be the following:

SELECT customers.customerName, SUM(orderdetails.quantityOrdered) AS total_orders
FROM orderdetails
JOIN orders ON orders.orderNumber = orderdetails.orderNumber
JOIN customers ON orders.customerNumber = customers.customerNumber
WHERE customers.customerName = 'Herkku Gifts'
GROUP BY customers.customerName;

Hope it can help to add it to the great work that you already have done, thanks!

**Comment by harsha547** [comment]
Thank you @alessandro-maccario 

can you create Pull Request with suggested changes ?

**Comment by alessandro-maccario** [comment]
Sure thing, I'll open it as soon as possible!

Thank you very much!
