### ISSUE TITLE
Missing query.07 from JOIN exercises

### ISSUE THREAD

**Issue by alessandro-maccario** [harsha547/ClassicModels-Database-Queries#2]
I cannot find the solution about the query n. 07 in the JOIN section in the repo, namely:

-- 7.Who are the employees in Boston?

I created two solutions, one using JOIN, the other using a subquery:

-- JOIN solution
SELECT CONCAT(employees.lastName, " ", employees.firstName) AS employees_name, offices.city
FROM employees
JOIN offices ON employees.officeCode = offices.officeCode
WHERE offices.city = 'Boston';

-- SUBQUERY solution
SELECT CONCAT(employees.lastName, " ", employees.firstName) AS employees_name
FROM employees
WHERE employees.officeCode IN (SELECT offices.officeCode
							   FROM offices
                               WHERE city = 'Boston');

Thanks again for your great work!

**Comment by harsha547** [comment]
@alessandro-maccario  Please create pull request for the changes that you are suggesting..
